### PR TITLE
Fix for graphql-core==3.2.0

### LINKED ISSUE #21: ImportError: cannot import name 'TypeFieldResolvers' from 'graphql.type.introspection'
This lib is not working with **graphql-core==3.2.0**

```python
Traceback (most recent call last):
  File "tests/scripts/validate_schema_is_up_to_date.py", line 3, in <module>
    from schemadiff import diff
  File "/src/virtualenv/lib/python3.7/site-packages/schemadiff/__init__.py", line 6, in <module>
    from schemadiff.diff.schema import Schema
  File "/src/virtualenv/lib/python3.7/site-packages/schemadiff/diff/schema.py", line 10, in <module>
    from graphql.type.introspection import TypeFieldResolvers
ImportError: cannot import name 'TypeFieldResolvers' from 'graphql.type.introspection' (/src/virtualenv/lib/python3.7/site-packages/graphql/type/introspection.py)
```

### PR DESCRIPTION
**Pull request by romeroyonatan**
Fixes #21 

* Update the class name

### CODE REVIEW

**Comment by Ambro17** [comment]
Thank you for your contribution! I've run the tests against latest `graphql-core` and version `3.0.1` and they still pass so i'll proceed with the merge.

Please consider funding this open source project if your company uses it to provide value
