### ISSUE TITLE
ImportError: cannot import name 'TypeFieldResolvers' from 'graphql.type.introspection'

### ISSUE THREAD

**Issue by romeroyonatan** [Ambro17/graphql-schema-diff#21]
This lib is not working with **graphql-core==3.2.0**

```python
Traceback (most recent call last):
  File "tests/scripts/validate_schema_is_up_to_date.py", line 3, in <module>
    from schemadiff import diff
  File "/src/virtualenv/lib/python3.7/site-packages/schemadiff/__init__.py", line 6, in <module>
    from schemadiff.diff.schema import Schema
  File "/src/virtualenv/lib/python3.7/site-packages/schemadiff/diff/schema.py", line 10, in <module>
    from graphql.type.introspection import TypeFieldResolvers
ImportError: cannot import name 'TypeFieldResolvers' from 'graphql.type.introspection' (/src/virtualenv/lib/python3.7/site-packages/graphql/type/introspection.py)
```
